---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mycaet40/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
    - export BACKENDPATH=/home/mycaet40/mycaetracker-backend/
    - /bin/mkdir -p $BACKENDPATH
    - /bin/cp -R backend/dist $BACKENDPATH
    - /bin/cp backend/package.json $BACKENDPATH
    - /bin/cp backend/package-lock.json $BACKENDPATH
    - if [ ! -f $BACKENDPATH.env ]; then /bin/cp backend/.env.example $BACKENDPATH.env; fi
